### PR TITLE
Database read

### PR DESCRIPTION
**Pull request by R03SMUS**
Read from database with SQL queries. 

### ALL BELOW GENERATED WITH COPILOT, BUILD IN GITHUB ACTION. 
This pull request introduces a new `CheepViewModel` project and refactors the existing code to use this new project. It also includes enhancements to the database interaction logic.

### Project Structure Changes:
* Added a new project `CheepViewModel` to the solution (`Chirp.sln`) and configured it for build configurations. [[1]](diffhunk://#diff-c8e60c0fbc3b616b054ab808249f9b16871d53846b91e24057f47a68010f8f40R22-R23) [[2]](diffhunk://#diff-c8e60c0fbc3b616b054ab808249f9b16871d53846b91e24057f47a68010f8f40R57-R60) [[3]](diffhunk://#diff-c8e60c0fbc3b616b054ab808249f9b16871d53846b91e24057f47a68010f8f40R69)

### Code Refactoring:
* Moved the `CheepViewModel` record definition to the new `CheepViewModel` project (`src/CheepViewModel/CheepViewModel.cs`).
* Updated `CheepService` and related classes to use the new `CheepViewModel` namespace. [[1]](diffhunk://#diff-4cdde344fe1e7faa186560dbaca16e20cfd920473cb7f0c2dbf52aef06929f7eR2-R32) [[2]](diffhunk://#diff-64283d2a0379ec0b088e5c6e660e5dcb1beac4bf3453e2db8c4b5c244ccafebcL9-R9) [[3]](diffhunk://#diff-360ec53b6329d48304cb84d72d7f6d9488ad0eb19a0eae2eb8d1eb93eaa55475L9-R9)

### Database Enhancements:
* Added a project reference to `CheepViewModel` in `Chirp.SQLite.csproj`.
* Enhanced `DBFacade` to support reading cheeps from a specific author and refactored the connection handling. [[1]](diffhunk://#diff-0072bd5a723df59ba064ff48324dc25824a37169127310754a64229565142e12L4-R7) [[2]](diffhunk://#diff-0072bd5a723df59ba064ff48324dc25824a37169127310754a64229565142e12L30-R36) [[3]](diffhunk://#diff-0072bd5a723df59ba064ff48324dc25824a37169127310754a64229565142e12L48-R115)
* Updated `IDatabaseRepository` interface to include the new method for reading cheeps by author.

### Additional Changes:
* Added dependency injection setup for `ICheepService` in `Program.cs` (commented out for now).

### CODE REVIEW

**Comment by MathiasJohneck** [comment]
Do we care about .net test here?

**Comment by R03SMUS** [comment]
for me testing locally it passes the tests, i think its because of something with the database, not being setup correctly. so i would say no.

**Comment by MathiasJohneck** [comment]
Den giver en fejl hvis man forsøger at køre chirp.razor, da både SQLite og cheepViewModel er sat til dotnet 8, som giver fejl hvis man forsøger at køre det på en maskine der kun har dotnet 7

**Comment by MathiasJohneck** [comment]
If manually changed to dotnet 7 and run, then it cannot locate the database, it gives a network 500 error. full stacktrace error attached: 
[Stacktrace network 500 error.txt](https://github.com/user-attachments/files/17196581/Stacktrace.network.500.error.txt)

**Comment by R03SMUS** [comment]
hmm. that might be a problem with the path to the chirp.db file. might need some help on this one

**Comment by Joha6210** [comment]
@R03SMUS Yes, I am experiencing the same issue...

**Comment by Joha6210** [comment]
I'am also experiencing this error message:
image
Maybe we are pointing to a different .db file?

**Comment by R03SMUS** [comment]
try running the program with this in *wsl*, does not work on windows

**CHIRPDBPATH=../Chirp.SQLite/data/chirp.db dotnet run**

**Comment by R03SMUS** [comment]
ok, so it should not be dependant on a database now (if not provided it will create a tempdb). i still fails on github, but should work locally.

**Comment by MathiasJohneck** [comment]
it works if given: `CHIRPDBPATH=../Chirp.SQLite/data/chirp.db dotnet run` but not if run without.

**Comment by R03SMUS** [comment]
are you on the newest commit?

**Comment by MathiasJohneck** [comment]
yes

**Comment by MathiasJohneck** [comment]
Test run locally

**Pull request merged**
